### ISSUE TITLE
ShowAllActivities

### ISSUE THREAD

**Issue by Beikkn** [Vencord/plugin-requests#546] opened 2024-05-13 19:17 UTC
### Plugin Description

![Screenshot 2024-05-13 204800](https://github.com/Vencord/plugin-requests/assets/169714560/e0cf674e-cea1-478c-a105-bde24e0af514)

Showing all activities that a user has enabled, using arrows to navigate between them.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/ShowAllActivities

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by D3SOX** [comment] 2024-05-13 19:22
Duplicate of #258

**Comment by Beikkn** [comment] 2024-05-13 19:23
> Duplicate of #258

sorry but i'm not gonna scroll through literally 300 suggestions

**Comment by D3SOX** [comment] 2024-05-13 19:24
Feel free to do whatever you want but this is going to be closed ^^

**Comment by EdVraz** [comment] 2024-05-13 19:44
> > Duplicate of #258
> 
> sorry but i'm not gonna scroll through literally 300 suggestions

Dont open an issue then, dipshit.

**Closed by EdVraz** 2024-05-13 19:44 UTC

**Comment by Beikkn** [comment] 2024-05-13 21:14
> > > Duplicate of #258
> > 
> > 
> > sorry but i'm not gonna scroll through literally 300 suggestions
> 
> Dont open an issue then, dipshit.

So much for professionalism..

**Comment by EdVraz** [comment] 2024-05-13 21:22
> > > > Duplicate of #258
> > > 
> > > 
> > > sorry but i'm not gonna scroll through literally 300 suggestions
> > 
> > 
> > Dont open an issue then, dipshit.
> 
> So much for professionalism..

So much for following request creation rules..

**Comment by Beikkn** [comment] 2024-05-13 21:25
if you're not getting paid properly then do something else than shit on people that have valid requests and reason.

**Comment by D3SOX** [comment] 2024-05-13 21:34
> valid requests

posts an invalid requests

**Comment by EdVraz** [comment] 2024-05-13 21:37
> if you're not getting paid properly then do something else than shit on people that have valid requests and reason.

A: sarcasm exists
B: cry me a river
C: this is volunteer work and you're wasting OUR time by not checking if your request already exist so I CAN be rude for you unreasoned and invalid wasting of my

**Comment by Golonchy** [comment] 2024-05-14 04:24
moral of the story:
read the rules {husk}

**Comment by radishcatish** [comment] 2024-05-14 04:53
![mrrrow](https://github.com/Vencord/plugin-requests/assets/166326616/25cdcf5c-db86-4d67-a2c8-0757fce58c63)
look at thsi reaqlly rfreaking funny cat i  have on my computer
