### ISSUE TITLE
updating message logger to log all images to a folder

### ISSUE THREAD

**Issue by 4ktreyguap** [Vencord/plugin-requests#801] opened 2024-06-27 00:03 UTC
### Plugin Description

correct me if im wrong but in the settings for the message logger I dont see an option to save all images to a folder. It would be nice if this feature was replicated from betterdiscord's old message logger where literally every image could be permanently saved to a folder. 

### Existing Plugin for other mod

this is an update for the message logger, not asking for a whole new one

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment] 2024-06-27 00:29
duplicate of countless issues

vencord maintainers have already decided that permanent saving wasn't to be added to messagelogger, as it's outright creepy and unsustainable on long term to store all images and message content

**Closed** 2024-06-27 08:20 UTC
