### ISSUE TITLE
A personal Pin for your own.

### ISSUE THREAD

**Issue by zymcs** [Vencord/plugin-requests#196] opened 2024-03-15 14:17 UTC
### Plugin Description

This plugin is very simple and I think should be implemented officially, Usually, you cannot pin anything in any server unless you are of a role that has permission to do so, Or in DMS if you want to pin something it shows the user the message you pin'd and whatever.
However, this plugin idea is that you yourself have your own personal pin that you can pin and it is client-sided to yourself, Could pin images, messages, anything as long as it is a pin. and I think it should be ontop here
![image](https://github.com/Vencord/plugin-requests/assets/163318500/d5887be3-45c9-4339-87ce-745ad5471e59)
With a different logo to it so you know it's client sided, also another suggestion is that the typical Right click to add it into personal pin.
Would be a nice suggestion :)

### Existing Plugin for other mod

Nope

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Roki100** [comment] 2024-03-15 21:10
[#2246](https://github.com/Vendicated/Vencord/pull/2246)

**Comment by EdVraz** [comment] 2024-03-15 21:21
Erm ackshually this is a duplicate of #75

**Closed by EdVraz** 2024-03-15 21:21 UTC

**Comment by zymcs** [comment] 2024-03-16 02:33
I checked through and didn't see anyone posting it until you guys linked similar ones. Apologies.
On that note, How long would it take for that plugin to finish? and would it be official or third party?

**Comment by nin0-dev** [comment] 2024-03-16 10:36
A pull request is pending, so it should soon be merged as an official plugin
