### ISSUE TITLE
Volum spotify

### ISSUE THREAD

**Issue by labicbretagne** [Vencord/plugin-requests#865] opened 2024-07-08 18:15 UTC
### Plugin Description

Add the volume bar for the spotify music that is displayed at the top of our discord profile thanks to the plugins "Spotify Control"

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Krammeth** [comment] 2024-07-08 18:18
Right click on the album image
Also, pretty sure this is a duplicate of older issues

**Comment by labicbretagne** [comment] 2024-07-08 18:23
> Faites un clic droit sur l’image de l’album Aussi, je suis presque sûr qu’il s’agit d’un doublon d’anciens numéros
> 
> edit : l’a trouvé, #293

Oh yes indeed, maybe more practical to put it directly displayed. If you understand because I translate on google translate

**Closed** 2024-07-09 14:46 UTC
