### ISSUE TITLE
YouTubeMusicControl

### ISSUE THREAD

**Issue by barraIhsan** [Vencord/plugin-requests#402] opened 2024-04-24 06:39 UTC
### Plugin Description

The same thing as SpotifyControl but for YouTube Music, I don't know if this is currently possible or not, maybe connect the google acc to vencord? Similar to #337 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by auxtinn** [comment] 2024-04-24 06:43
SpotifyControl uses the user's OAuth-connected Spotify account, and grabs the user's Spotify token from that to enable the playback features inside of Discord, so I don’t think this would be possible unless Vencord added a YouTube/Music OAuth just for this plugin.

**Comment by Sqaaakoi** [comment] 2024-04-24 06:46
duplicate of #198

**Comment by Ermageeerd** [comment] 2024-06-15 07:03
> duplicate of #198

Isn't that for Rhythmbox, Not YouTube Music? or is Rhythmbox an engine or API and I'm just stupid.

**Comment by Vendicated** [comment] 2024-06-15 20:06
edited 198. closing in favour of it

**Closed by Vendicated** 2024-06-15 20:06 UTC
