### ISSUE TITLE
Edit Users (And Servers)

### ISSUE THREAD

**Issue by WickerKeli** [Vencord/plugin-requests#384] opened 2024-04-21 18:26 UTC
### Plugin Description

Locally lets you modify the image and nickname of users

I tend to have issues with people constantly changing their profile picture and name quite a lot, and this would be very good QOL to avoid getting confused after not talking to someone for a while because they changed their name/profile picture

### Existing Plugin for other mod

https://betterdiscord.app/plugin/EditUsers

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Grafaffel** [comment] 2024-04-21 18:30
duplicate of #102, please check before opening a new issue 🙏

**Closed** 2024-04-21 19:06 UTC
