### ISSUE TITLE
Channeltabs

### ISSUE THREAD

**Issue by xxkalishxx** [Vencord/plugin-requests#733] opened 2024-06-17 17:28 UTC
### Plugin Description

A Plugin which gives the option to have different tabs in Discord and set up favourites.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/ChannelTabs

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Z4ne4what** [comment] 2024-06-17 18:08
Brother just use the experiments plugin and then nab favorites server from within it. Its a lot faster than tabs. 👍

**Comment by nin0-dev** [comment] 2024-06-17 18:57
As of now, you will start using a very nice feature: the search bar

(dupe of #6)

**Closed** 2024-06-17 21:01 UTC
Labels: rejected (duplicate)
