### ISSUE TITLE
FakeBadge

### ISSUE THREAD

**Issue by MrLucaverus** [Vencord/plugin-requests#395] opened 2024-04-22 23:49 UTC
### Plugin Description

Adds the ability to add discord badges to the profile, which cannot be obtained by ordinary mortals. 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by MrDiamondDog** [comment] 2024-04-23 00:05
dupe of #318 #194

**Closed** 2024-06-09 14:49 UTC
