### ISSUE TITLE
GIF Folders

### ISSUE THREAD

**Issue by Ionxn** [Vencord/plugin-requests#233] opened 2024-03-24 07:18 UTC
### Plugin Description

I think it would be beneficial for almost every discord user to have a plugin that would allow them to categorize their gifs.
I'm sure we all have hundreds of gifs saved, and in order to find the one you want, you need to scroll.
If we have a plugin where we can create folders for said gifs, in order to organize them better, it would make quality of life far better. 

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment] 2024-03-24 07:24
duplicate of #44

**Closed** 2024-03-24 07:26 UTC
Labels: rejected (duplicate)
