### ISSUE TITLE
Discord badges (on Vencord)

### ISSUE THREAD

**Issue by mrxHXD** [Vencord/plugin-requests#444] opened 2024-04-30 11:37 UTC
### Plugin Description

**BEST PLUGIN** #viral #vencord
_Please creat an Vencord Plugin that allows to use badge(only in that preview on vencord users). Special badges like Staff etc. and custome ones that we can creat._ 

### Existing Plugin for other mod

No, it does not exist

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Grafaffel** [comment] 2024-04-30 11:42
> ### Plugin Description
> **BEST PLUGIN** #viral #vencord _Please creat an Vencord Plugin that allows to use badge(only in that preview on vencord users). Special badges like Staff etc. and custome ones that we can creat._
> 
> ### Existing Plugin for other mod
> No, it does not exist
> 
> ### Request Agreement
> * [x]  I read the above and made sure my plugin is possible and allowed
> * [x]  I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
> * [x]  I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

You can Sponsor this Project for such perms

**Comment by nin0-dev** [comment] 2024-04-30 12:08
Duplicate of #318

**Comment by EdVraz** [comment] 2024-04-30 20:50
Great suffering awaits you.

**Closed by EdVraz** 2024-04-30 20:50 UTC

**Comment by mrxHXD** [comment] 2024-05-03 19:07
Wtf why??

**Comment by mrxHXD** [comment] 2024-05-03 19:12
Some other things are not necessary either...
