### ISSUE TITLE
stereo

### ISSUE THREAD

**Issue by xvzrnxv** [Vencord/plugin-requests#779] opened 2024-06-24 00:26 UTC
### Plugin Description

Adds stereo sound to your Discord Client.

### Existing Plugin for other mod

https://www.mediafire.com/file/6vmfvxy0mqtkfeo/edoStereo.plugin.js/file

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by xvzrnxv** [comment] 2024-06-24 00:27
/**
 * @name edoStereo
 * @version 0.0.5
 * @description Adds stereo sound to Discord. Better Discord v1.9.5
 * @authorLink https://github.com/edoderg
 * @website https://edoderg.github.io/
 * @source https://github.com/edoderg/edoStereo
 * @invite fgMC6SetXk
 * @updateUrl https://github.com/edoderg/edoStereo/blob/main/edoStereo.plugin.js
 */
module.exports = (() => {
  const config = {
    // configuration object for the plugin
    main: "index.js",
    info: {
      name: "edoStereo",
      authors: [{ name: "ed.o", discord_id: "269831113919299584" }],
      version: "0.0.5",
      description:
        "Adds stereo sound to your Discord Client. Better Discord v1.9.5",
    },
    changelog: [
      {
        title: "Changelog",
        items: ["BetterDiscord Stereo Sound for 1.9.5", "Added an option to change your bitrate", "Added an notification when joining voice channel", "Removed unnecessary stuff"]
      }
    ],
    defaultConfig: [
      // default configuration options for the plugin
      {
        type: "switch",
        id: "enableToasts",
        name: "Enable notifications",
        note: "Warning for Discord Audio Features",
        value: true,
      },
      {
        type: "dropdown",
        id: "stereoChannelOption",
        name: "Stereo Channel Option",
        note: "Select your preferred channel option",
        value: "7.1",
        options: [
          { label: "1.0 Mono Sound", value: "1.0" },
          { label: "2.0 Normal Stereo Sound", value: "2.0" },
          { label: "7.1 Surround Sound (Default)", value: "7.1" },
        ],
      },
      {
        type: "dropdown",
        id: "bitrateOption",
        name: "Bitrate Option",
        note: "Select your preferred bitrate",
        value: "512000",
        options: [
            { label: "8kbps", value: "8000" }, // 🗑️
            { label: "48kbps", value: "48000" },
            { label: "128kbps", value: "128000" },
            { label: "512kbps (Default)", value: "512000" },
        ],
      },
      {
        type: "category",
        id: "otherSettings",
        name: "Miscellaneous",
        shown: true,
        settings: [
          {
            type: "switch",
            id: "comingSoon1",
            name: "New Features", // 💔
            note: "New Features",
            value: false,
            disabled: true,
          },
        ],
      },
    ],
  };
  return !global.ZeresPluginLibrary
    ? class {
        // placeholder for when zerespluginlibrary is missing
        constructor() {
          this._config = config;
        }
        getName() {
          return config.info.name;
        }
        getAuthor() {
          return config.info.authors.map((a) => a.name).join(", ");
        }
        getDescription() {
          return config.info.description;
        }
        getVersion() {
          return config.info.version;
        }
        load() {
          // show modal to install zerespluginlibrary
          BdApi.showConfirmationModal(
            "[edoStereo] Library Missing",
            `ZeresPluginLibrary is missing. Click "Install Now" to download it.`,
            {
              confirmText: "Install Now",
              cancelText: "Cancel",
              onConfirm: () => {
                require("request").get(
                  "https://rauenzi.github.io/BDPluginLibrary/release/0PluginLibrary.plugin.js",
                  async (error, response, body) => {
                    if (error) {
                      console.error("Error downloading ZeresPluginLibrary:", error);
                      BdApi.showConfirmationModal(
                        "Download Error",
                        "An error occurred while downloading ZeresPluginLibrary. Please try again later or download it manually from the official website.",
                        {
                          confirmText: "OK",
                          cancelText: "Cancel",
                        }
                      );
                      return;
                    }
                    await new Promise((r) =>
                      require("fs").writeFile(
                        require("path").join(
                          BdApi.Plugins.folder,
                          "0PluginLibrary.plugin.js"
                        ),
                        body,
                        r
                      )
                    );
                  }
                );
              },
            }
          );
        }
        start() {}
        stop() {}
      }
    : (([Plugin, Api]) => {
        // actual plugin implementation when zerespluginlibrary is available
        const plugin = (Plugin, Library) => {
          const { WebpackModules, Patcher, Toasts } = Library;
          return class edoStereo extends Plugin {
            // plugin start method
            onStart() {
              BdApi.UI.showNotice("[edoStereo v.0.0.5] You can now use edoStereo! 😉", { type: "info", timeout: 5000 });
              this.settingsWarning();
              this.justJoined = false;
              const voiceModule = WebpackModules.getModule( BdApi.Webpack.Filters.byPrototypeFields("updateVideoQuality") );
              // patch discord's voice module to enable stereo sound
              BdApi.Patcher.after("edoStereo", voiceModule.prototype, "updateVideoQuality", (thisObj, _args, ret) => {
                  if (thisObj) {
                    const setTransportOptions = thisObj.conn.setTransportOptions;
                    const channelOption = this.settings.stereoChannelOption;
                    const selectedBitrate = this.settings.bitrateOption; 

                    thisObj.conn.setTransportOptions = function (obj) {
                      if (obj.audioEncoder) {
                        obj.audioEncoder.params = {
                          stereo: channelOption,
                        };
                        obj.audioEncoder.channels = parseFloat(channelOption);
                        obj.encodingVoiceBitRate = parseInt(selectedBitrate);
                      }
                      if (obj.fec) {
                        obj.fec = false; // disable forward error correction (fec)
                      }
                      if (obj.encodingVoiceBitRate < selectedBitrate) {
                          obj.encodingVoiceBitRate = selectedBitrate; // added
                      }
                      setTransportOptions.call(thisObj.conn, obj);
                      if (!this.justJoined) {
                        Toasts.show("You're using edoStereo now!", { type: "info", timeout: 5000 });
                        this.justJoined = true;
                      }
                    };
                    return ret;
                  }
                }
              );
              const voiceConnectionModule = WebpackModules.getByProps("hasVideo", "disconnect", "isConnected");
              this.disconnectPatcher = BdApi.Patcher.after("edoStereo", voiceConnectionModule, "disconnect", () => {
                this.justJoined = false;
              });
            }
            // display settings warning
            settingsWarning() {
              const voiceSettingsStore = WebpackModules.getByProps(
                "getEchoCancellation"
              );
              if (
                voiceSettingsStore.getNoiseSuppression() ||
                voiceSettingsStore.getNoiseCancellation() ||
                voiceSettingsStore.getEchoCancellation()
              ) {
                if (this.settings.enableToasts) {
                  // show a toast notification for user
                  Toasts.show(
                    "Please disable echo cancellation, noise reduction, and noise suppression for edoStereo",
                    { type: "warning", timeout: 5000 }
                  );
                }
                return true;
              } else return false;
            }
            // plugin stop method
            onStop() {
              Patcher.unpatchAll();
              if (this.disconnectPatcher) this.disconnectPatcher();
            }
            // creating settings panel
            getSettingsPanel() {
              const panel = this.buildSettingsPanel();
              const noteElement = document.createElement("div");
              noteElement.className = "edoStereo-settings-note";
              noteElement.textContent = "Note: After changing any setting, please rejoin the voice channel for the changes to take effect.";
              noteElement.style.color = "#FF0000";
              noteElement.style.marginTop = "10px";
              panel.append(noteElement);
              return panel.getElement();
            }
          };
        };
        return plugin(Plugin, Api);
      })(global.ZeresPluginLibrary.buildPlugin(config));
})();



the code

**Comment by nin0-dev** [comment] 2024-06-24 00:34
read the request rules next time

also stereo mic isn't possible, since your sound is "mono"ised server side.

**Comment by MrDiamondDog** [comment] 2024-06-24 01:13
> - [X] I read the above and made sure my plugin is possible and allowed
> - [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
> - [X] I checked every box, despite not reading any
> - [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

1. It's not possible
2. Duplicate of #366
3. You didn't read any of the request rules

**Comment by xvzrnxv** [comment] 2024-06-24 01:15
> read the request rules next time
> 
> also stereo mic isn't possible, since your sound is "mono"ised server side.

its possible we can deadass hop in a vc 🤦‍♂️

**Comment by xvzrnxv** [comment] 2024-06-24 01:15
> > * [x]  I read the above and made sure my plugin is possible and allowed
> > * [x]  I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
> > * [x]  I checked every box, despite not reading any
> > * [x]  I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist
> 
> 1. It's not possible
> 2. Duplicate of [Stereo Mic is 100% Possible 😭  #366](https://github.com/Vencord/plugin-requests/issues/366)
> 3. You didn't read any of the request rules
> 
> If you are going to make another plugin request, please read everything

if its not possible then how am i using it in betterdiscord ?

**Comment by MrDiamondDog** [comment] 2024-06-24 01:16
It's placebo. Discord does not send stereo audio to any other user, but makes any stereo audio mono. This has been proven and it's in the request rules.

**Comment by MrDiamondDog** [comment] 2024-06-24 01:19
> > It's placebo. Discord does not send stereo audio to any other user, but makes any stereo audio mono. This has been proven and it's in the request rules.
> 
> 
> 
> i have an alt to listen to myself using it, u mind hopping in vc for me to show u

You don't have to show me cause it's not possible. It's in the request rules for a reason

**Comment by xvzrnxv** [comment] 2024-06-24 01:38
> > > It's placebo. Discord does not send stereo audio to any other user, but makes any stereo audio mono. This has been proven and it's in the request rules.
> > 
> > 
> > i have an alt to listen to myself using it, u mind hopping in vc for me to show u
> 
> You don't have to show me cause it's not possible. It's in the request rules for a reason


https://github.com/Vencord/plugin-requests/assets/106571334/3c9652b0-6fda-48f0-a3ba-b24a13def463

explain this then smart guy

**Comment by xvzrnxv** [comment] 2024-06-24 01:53
> > > It's placebo. Discord does not send stereo audio to any other user, but makes any stereo audio mono. This has been proven and it's in the request rules.
> > 
> > 
> > i have an alt to listen to myself using it, u mind hopping in vc for me to show u
> 
> You don't have to show me cause it's not possible. It's in the request rules for a reason


https://github.com/Vencord/plugin-requests/assets/106571334/22bb424e-0199-4669-8b4d-0ec6e3b9f0fc

here im panned all the way to the right

**Comment by Scyye** [comment] 2024-06-24 02:45
![image](https://github.com/Vencord/plugin-requests/assets/97131358/3f4c5552-906b-478e-84ff-2cd0bf874d10)
nice.

**Comment by xvzrnxv** [comment] 2024-06-24 03:45
> ![image](https://private-user-images.githubusercontent.com/97131358/342185604-3f4c5552-906b-478e-84ff-2cd0bf874d10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDA5ODksIm5iZiI6MTcxOTIwMDY4OSwicGF0aCI6Ii85NzEzMTM1OC8zNDIxODU2MDQtM2Y0YzU1NTItOTA2Yi00NzhlLTg0ZmYtMmNkMGJmODc0ZDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAzNDQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZWZlNzc1YzdiNWYzMmFhOGU2M2I2NmYyZTU5YzFiY2QyMGMwZTA0Zjc2N2I4ZWUwYTIzNzlkZjQ3NGNhZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SXmCK74Gi5-U6c2C3Dkx6VnOzfYx6XGalqsE5r6Nnvc) nice.

i rlly dont care about any of that bs just wanted to put up a suggestion

**Comment by Scyye** [comment] 2024-06-24 03:59
you seem like a lovely fellow.

**Closed** 2024-06-24 11:30 UTC

**Comment by Dr-Flay** [comment] 2024-07-05 07:52
I am a radio show host for a local radio station. I have been using stereo over discord for several years to record my show with guests.
I use ripcord for my end and so do the co-hosts and guests that need to inject stereo audio, so they can play and control the music from their end (my regular co-host also uses a stereo mic).
Ripcord allows overriding the server restrictions, so you can not only enable stereo but enable full unrestricted music encoding mode.
Participants using real discord hear stereo but only at the quality set for the room in the server settings.
Ripcord users hear full music quality stereo.

Placebo ? Certainly not or my stereo music radio show would have had serious problems for the past few years.

**Comment by MrDiamondDog** [comment] 2024-07-05 13:31
Yes, we were wrong, it is possible. I was lead to believe it wasn't for a while

We still aren't adding it as a plugin cause it is pretty useless for any normal user

**Comment by Dr-Flay** [comment] 2024-07-09 23:48
...any normal user doesn't use vencord.
People use vencord to add not normal features.
