### ISSUE TITLE
Toggle Hide modded client features

### ISSUE THREAD

**Issue by D3anDark** [Vencord/plugin-requests#878] opened 2024-07-10 01:10 UTC
### Plugin Description

This plugin allows you to set shortcut, to change visibility of every visible part that is saying “hey it's modded client”. This will be good for users that want to send screenshot on a server where modded clients are restricted.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Luna-devv** [comment] 2024-07-10 01:11
Just use a browser for screenshots

**Comment by D3anDark** [comment] 2024-07-10 01:17
> Just use a browser for screenshots

yeah, I can do it, but sometimes I did forget about it, and don't do it, but by muscle memory I can do it everytime

**Comment by Luna-devv** [comment] 2024-07-10 01:18
Many plugins require restarts to take affect, it's not really possible to "just remove" any added or modified component

**Comment by ImLvna** [comment] 2024-07-10 01:19
being able to toggle modded features would require an extreme refactor of every plugin that adds things to the ui, and toggling them would lag the app as it is updating every modded element at once. this is most likely not going to be implimented

**Comment by D3anDark** [comment] 2024-07-10 01:49
> Many plugins require restarts to take affect, it's not really possible to "just remove" any added or modified component

It can be in CSS quick `display: none;` in every modded component and make every quick CSS and theme in comment. This will be quick and I think smooth.

**Comment by ImLvna** [comment] 2024-07-10 01:51
its not that simple. additionally, some plugins have hardcoded css in that cannot be disabled

**Comment by D3anDark** [comment] 2024-07-10 01:51
> being able to toggle modded features would require an extreme refactor of every plugin that adds things to the ui, and toggling them would lag the app as it is updating every modded element at once. this is most likely not going to be implimented

i don't think make for every modded element one command in css will be that hard>

`
[put here modded classes/id's] {
display: none; !important
}
`

**Comment by Luna-devv** [comment] 2024-07-10 01:51
A class name for that would have to be added to every component, yet this wouldn’t solve components which were modified.

Though if you think you have the solution, open a PR

**Comment by jamesbt365** [comment] 2024-07-10 02:17
A duplicate issue of this was closed less than 1 day ago.

Duplicate of #786.

**Closed** 2024-07-10 02:29 UTC
