### ISSUE TITLE
RelativeTimestamps

### ISSUE THREAD

**Issue by etotspia5** [Vencord/plugin-requests#690] opened 2024-06-07 17:48 UTC
### Plugin Description

![Screenshot_73](https://github.com/Vencord/plugin-requests/assets/170802082/9a109d81-ae7c-4be1-98c0-e59730f7fc5d)

Adds: 1s, 1m, 1h, 1y to Messages that send every Messages send.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Feathers8** [comment] 2024-06-07 18:01
Looks like a duplicate of #1. You can show your support for it by clicking on the 👍.

**Closed** 2024-06-07 18:10 UTC
