### ISSUE TITLE
last message date

### ISSUE THREAD

**Issue by Beikkn** [Vencord/plugin-requests#543] opened 2024-05-13 19:10 UTC
### Plugin Description

![Screenshot 2024-05-13 204729](https://github.com/Vencord/plugin-requests/assets/169714560/4b70c396-0a06-414d-ae12-14a671826a89)
basically shows when a user sent their last message (QoL)

### Existing Plugin for other mod

https://betterdiscord.app/plugin/LastMessageDate

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment] 2024-05-14 02:49
duplicate of https://github.com/Vencord/plugin-requests/issues/235

**Closed by Vendicated** 2024-05-14 02:49 UTC
