### ISSUE TITLE
Friend Notification Plugin request 

### ISSUE THREAD

**Issue by ImExtrimis** [Vencord/plugin-requests#933] opened 2024-07-22 18:43 UTC
### Plugin Description

Hey ive been using Vencord for like almost a year now and i feel like there should be this 1 feature
Better discord has it but i could not find it on vencord 
its the Friend Notification... this plugin tells you if your friend changed the status or things like that
here is the link - https://betterdiscord.app/plugin/FriendNotifications
My Discord:- ImExtremis#0

![image](https://github.com/user-attachments/assets/a966e237-6b19-46b3-b496-ea99fa6d9923)

I would be really happy to have that inplemented in vencord
Thank you

### Existing Plugin for other mod

https://betterdiscord.app/plugin/FriendNotifications

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Faf4a** [comment] 2024-07-22 19:14
duplicate of #12

**Closed** 2024-07-22 19:20 UTC
Labels: rejected (duplicate)
