### ISSUE TITLE
complaint about loading quotes 

### ISSUE THREAD

**Issue by dizzsea** [Vencord/plugin-requests#129] opened 2024-02-28 08:10 UTC
### Plugin Description

i don't know if this is the right place to bring this up and i apologize if not

please allow us to disable certain loading quotes. i had the stupid vaporeon breeding joke appear while opening the app, and that joke is associated with trauma i have, not to mention that it's also just unfunny and zoophilic. i disabled the plugin but it would be nice to be able to use it by modifying it

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by dizzsea** [comment] 2024-02-28 08:11
sorry for sounding angry i just really cannot with that stupid copypasta

**Comment by dizzsea** [comment] 2024-02-28 08:22
edited this for brevity and language. i've calmed down, i'm sorry for sounding so harsh initially, i was just genuinely emotional about it

**Comment by Sqaaakoi** [comment] 2024-02-28 10:41
didn't even know this was listed as a quote as I don't use the plugin, imo the list 100% should be configurable, and built-in quotes should like that should be split off into an NSFW list or removed entirely

**Comment by Sqaaakoi** [comment] 2024-02-28 10:47
considering a lot of the recent changes in the actual vencord discord server due to people being very uncomfortable about being called cute, this being changed/removed would probably a good thing to do

**Comment by nvhhr** [comment] 2024-02-28 10:57
Related PR: https://github.com/Vendicated/Vencord/pull/1795
It doesn't allow modifying the quotes already in the plugin though, but does allow disabling them all.

Also not directly related but interesting: https://github.com/Vendicated/Vencord/pull/1729

**Comment by Vendicated** [comment] 2024-02-28 10:58
not a plugin request

duplicate of https://github.com/Vendicated/Vencord/issues/1654

**Closed by Vendicated** 2024-02-28 10:58 UTC

**Comment by lewisakura** [comment] 2024-05-17 21:16
fwiw, this will be removed in the latest version of the loadingquotes plugin, and apologies for it being left in and for it taking so long to be removed. it shouldn't have really been in the mod in the first place
