### ISSUE TITLE
option to hide users or blocked users from everywhere (member list, etc.)

### ISSUE THREAD

**Issue by yakisoba112** [Vencord/plugin-requests#713] opened 2024-06-12 14:13 UTC
### Plugin Description

a plugin to hide blocked users from the member list or anywhere.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Feathers8** [comment] 2024-06-12 14:32
Seems to be a duplicate of https://github.com/Vencord/plugin-requests/issues/187. You can show your support for it by clicking the 👍

**Closed** 2024-06-12 14:45 UTC
