### ISSUE TITLE
Plugin that allows to Locally Change Friends and your own Colors for any Server

### ISSUE THREAD

**Issue by Jaseliara** [Vencord/plugin-requests#209] opened 2024-03-19 15:34 UTC
### Plugin Description

As the title suggests what i would like to see is a Plugin that allows you to change The Colors in DM's and Servers for other Users, User on a server where u don't have Role Edit rights got a Color that is Badly readable for you? Just Change it Locally back.
A similar Plugin was made for Better Discord by Devilbro only his Plugin allowed for even more Control about another User (like Changing their name which is now a Feature of discord itself).

The Main Part about this is the Changes to them in Direct Messages so RoleColorAnywhere doesn't apply as that just changes them within Servers.

### Existing Plugin for other mod

https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/EditUsers

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment] 2024-04-04 21:35
duplicate of https://github.com/Vencord/plugin-requests/issues/102

**Closed by Vendicated** 2024-04-04 21:35 UTC
