### ISSUE TITLE
Custom Ringtone

### ISSUE THREAD

**Issue by hillyheights** [Vencord/plugin-requests#784] opened 2024-06-24 16:41 UTC
### Plugin Description

Lets you choose an audio from your files and import it to make it a ringtone.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Luna-devv** [comment] 2024-06-24 16:45
I would consider this related to #21

**Comment by hillyheights** [comment] 2024-06-24 16:48
i dont know how to get custom plugins lmao

**Comment by Scyye** [comment] 2024-06-24 16:49
thanks for telling us.

> i dont know how to get custom plugins lmao

**Comment by hillyheights** [comment] 2024-06-24 16:49
> thanks for telling us.
> 
> > i dont know how to get custom plugins lmao

youre welcome

**Comment by Luna-devv** [comment] 2024-06-24 16:50
Custom plugins are entirly unrelated to this issue, no?

**Comment by Scyye** [comment] 2024-06-24 16:50
thats my point ^

**Comment by hillyheights** [comment] 2024-06-24 16:51
did you not link a custom plugin

**Comment by Luna-devv** [comment] 2024-06-24 16:52
Did you even read anything? Your issue is a duplicate of an already existing issues.

**Comment by hillyheights** [comment] 2024-06-24 16:53
no it isnt

**Comment by hillyheights** [comment] 2024-06-24 16:54
i know you want your dick in luna stfu

**Comment by hillyheights** [comment] 2024-06-24 16:55
idgaf

**Comment by hillyheights** [comment] 2024-06-24 16:55
what does my account creation have to do with anything lmao

**Comment by hillyheights** [comment] 2024-06-24 16:55
quit being a fag

**Comment by hillyheights** [comment] 2024-06-24 16:55
no shit

**Comment by hillyheights** [comment] 2024-06-24 16:57
scyye wants you so bad its obv af

**Comment by AushevAhmad** [comment] 2024-06-24 16:58
> i dont know how to get custom plugins lmao

https://github.com/Vendicated/Vencord/blob/main/docs/1_INSTALLING.md now please close this issue

**Comment by hillyheights** [comment] 2024-06-24 16:58
ill think about it

**Comment by hillyheights** [comment] 2024-06-24 16:59
kill the faggot!!!

**Comment by AushevAhmad** [comment] 2024-06-24 16:59
And please
![CleanShot 2024-06-24 at 19 59 05](https://github.com/Vencord/plugin-requests/assets/113457231/7814b349-89a9-4419-8214-0515bc5e8c5c)

**Comment by hillyheights** [comment] 2024-06-24 17:00
oh my goodness.... im so sorry.... i didnt know i was hurting anyone! i swear!

**Closed** 2024-06-24 16:59 UTC
Labels: rejected (duplicate)

**Comment by hillyheights** [comment] 2024-06-24 17:00
scyye lmk when ur dick goes in luna ill wait

**Comment by AushevAhmad** [comment] 2024-06-24 17:01
> oh my goodness.... im so sorry.... i didnt know i was hurting anyone! i swear!

I'm going fucking feral rn... This is absolutely hilarious, mods, lock this convo ffs

**Comment by hillyheights** [comment] 2024-06-24 17:01
lmao 😭

**Comment by hillyheights** [comment] 2024-06-24 17:03
Hi

**Comment by hillyheights** [comment] 2024-06-24 17:05
so like

**Comment by hillyheights** [comment] 2024-06-24 17:05
when are you guys gonna make this a plugin

**Comment by hillyheights** [comment] 2024-06-24 17:05
lowkey would be tuff

**Comment by hillyheights** [comment] 2024-06-24 17:05
aww man!

**Comment by HAHALOSAH** [comment] 2024-06-24 17:08
just read the entire thread and y’all made my day
