### ISSUE TITLE
People that have role

### ISSUE THREAD

**Issue by KIZILANDO** [Vencord/plugin-requests#1086] opened 2024-08-29 20:02 UTC
### Plugin Description

The idea is a plugin that makes possible to see in a server all people that have a specific role.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by jamesbt365** [comment] 2024-08-29 20:14
Duplicate of #1032 #1011 #885 #770 #359 and #118

**Closed** 2024-08-29 22:22 UTC
Labels: rejected (blatantly duplicate)
